apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: "bad"
spec:
  selector:
    app: grafana
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
#  loadBalancerIP: 192.168.100.150
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: my-grafana
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
#        command: [ "sh", "-c"]
#        args:
#        - while true; do
#            echo -en '\n';
#            printenv MY_POD_IP;
#            sleep 2;
#          done;
#        env:
#          - name: MY_POD_IP
#            valueFrom:
#              fieldRef:
#                fieldPath: status.podIP
