apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "bad"
spec:
  selector:
    app: ftps
  ports:
    - name: ftps21
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftps20
      protocol: TCP
      port: 20
      targetPort: 20
    - name: ftps51
      protocol: TCP
      port: 31001
      targetPort: 31001
    - name: ftps52
      protocol: TCP
      port: 31002
      targetPort: 31002
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my-ftps
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 31001
        - containerPort: 31002
        imagePullPolicy: Never
        volumeMounts:
        - name: ftps-storage
          mountPath: /home/luser
      volumes:
      - name: ftps-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
